/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.ottbot.centralrelay.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import org.junit.jupiter.api.Test;

/**
 * Model tests for OttbotReleaseView
 */
class OttbotReleaseViewTest {
    private final OttbotReleaseView model = new OttbotReleaseView();

    /**
     * Model tests for OttbotReleaseView
     */
    @Test
    void testOttbotReleaseView() {
        // TODO: test OttbotReleaseView
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'version'
     */
    @Test
    void versionTest() {
        // TODO: test version
    }

    /**
     * Test the property 'service'
     */
    @Test
    void serviceTest() {
        // TODO: test service
    }

    /**
     * Test the property 'downloadUrl'
     */
    @Test
    void downloadUrlTest() {
        // TODO: test downloadUrl
    }

    /**
     * Test the property 'releaseChannel'
     */
    @Test
    void releaseChannelTest() {
        // TODO: test releaseChannel
    }

}
