/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.ottbot.centralrelay.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import dev.ottbot.centralrelay.model.OttbotReleaseView;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PageViewOttbotReleaseView
 */
class PageViewOttbotReleaseViewTest {
    private final PageViewOttbotReleaseView model = new PageViewOttbotReleaseView();

    /**
     * Model tests for PageViewOttbotReleaseView
     */
    @Test
    void testPageViewOttbotReleaseView() {
        // TODO: test PageViewOttbotReleaseView
    }

    /**
     * Test the property 'content'
     */
    @Test
    void contentTest() {
        // TODO: test content
    }

    /**
     * Test the property 'hasNextPage'
     */
    @Test
    void hasNextPageTest() {
        // TODO: test hasNextPage
    }

    /**
     * Test the property 'pageNumber'
     */
    @Test
    void pageNumberTest() {
        // TODO: test pageNumber
    }

    /**
     * Test the property 'totalCount'
     */
    @Test
    void totalCountTest() {
        // TODO: test totalCount
    }

    /**
     * Test the property 'totalPages'
     */
    @Test
    void totalPagesTest() {
        // TODO: test totalPages
    }

}
