/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.ottbot.centralrelay.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Test;

/**
 * Model tests for UserMeView
 */
class UserMeViewTest {
    private final UserMeView model = new UserMeView();

    /**
     * Model tests for UserMeView
     */
    @Test
    void testUserMeView() {
        // TODO: test UserMeView
    }

    /**
     * Test the property 'username'
     */
    @Test
    void usernameTest() {
        // TODO: test username
    }

    /**
     * Test the property 'displayName'
     */
    @Test
    void displayNameTest() {
        // TODO: test displayName
    }

    /**
     * Test the property 'roles'
     */
    @Test
    void rolesTest() {
        // TODO: test roles
    }

    /**
     * Test the property 'createdOn'
     */
    @Test
    void createdOnTest() {
        // TODO: test createdOn
    }

    /**
     * Test the property 'lastLogin'
     */
    @Test
    void lastLoginTest() {
        // TODO: test lastLogin
    }

}
